### ISSUE TITLE
Yuguang Zhang's Eagle Eye test and feedback

### ISSUE THREAD

**Issue by ZYG15552858099** [Sunknight1986/Eagle-Eye#2]
Hi Clark, I have read your README and used Eagle Eye. I think this is a really cool tool, especially when I look at the final result presentation in your readme file. I can see the architectural information of the city very clearly. These will be of great potential to urban planners and scholars.

On the other hand, I had a bit of a problem with the Eagle Eye. I guess maybe my laptop has a low configuration and can't run the maps I loaded in efficiently.

- This is the interface that appeared when I first opened Eagle Eye. I have solved the problem.
![~FA )IQQ591H3MW_5538A0V](https://user-images.githubusercontent.com/88922796/135311390-a3e780e3-dcb5-4f59-8794-3cf201a845cd.png)

I chose the port of Manila as the city for my study. When I put the map into File Path, I noticed that most of the components turned orange as shown in the image below. I tried to reconnect to the OSM, but it still didn't work.
![GD4 XHR( @B (GSU34$UH)P](https://user-images.githubusercontent.com/88922796/135311904-ac75091b-6c30-4afa-88af-94a7a8501dc1.png)

In Rhino I can see the base map of the city, but not the cube of the building. I was very sad about this because I was really looking forward to seeing something like what you showed in README. I was hoping you could give me some advice on how to display those cubes.
![UQO90048JVYH7C71WXU@%R2](https://user-images.githubusercontent.com/88922796/135312389-587d77ed-197d-4af0-b7a0-a1a63d57ea18.png)

Thank you very much for your Eagle Eye development.

**Comment by Sunknight1986** [comment]
Hi @ZYG15552858099, thanks for the feedback.
1, I think it is because your computer doesn't have the fonts I'm using in this definition. I'm glad I could solve it :)
2, I have just released a new version of Eagle Eye, and have tested using Manila's map. It should work this time. Hoping this time you could see what you want to :) Here is the link: https://github.com/Sunknight1986/Eagle-Eye/releases/tag/0.2.2

**Comment by ZYG15552858099** [comment]
Hello, Clark. Thank you for uploading Eagle Eye again. It worked successfully on my computer. I'm very pleased with the results. I saw clearly the distribution of buildings in Manila and London.

I don't have a problem with the Eagle Eye development, it perfectly represents the information you stated in the Readme. I think IT's hard for me to find any way to make it better. But if I had to make a suggestion, I might say maybe you could state why buildings near existing skyscrapers are going to get taller in the future, and whether the trend is steady or exponential.

Overall, thanks again for re-tuning the Eagle Eye for me, it's very useful.

**Comment by ZYG15552858099** [comment]
Hello, Clark. Thank you for uploading Eagle Eye again. It worked successfully on my computer. I'm very pleased with the results. I saw clearly the distribution of buildings in Manila and London.
![RVW)F${(F2V34PVK4SZ%H6W](https://user-images.githubusercontent.com/88922796/135764717-b5f8ebb2-570a-4f32-a5a3-8e9e1ea19b36.png)

I don't have a problem with the Eagle Eye development, it perfectly represents the information you stated in the Readme. I think IT's hard for me to find any way to make it better. But if I had to make a suggestion, I might say maybe you could state why buildings near existing skyscrapers are going to get taller in the future, and whether the trend is steady or exponential.

Overall, thanks again for re-tuning the Eagle Eye for me, it's very useful.
